---
title: "Golden State Warriors Report"
font: 12pt
date: "March 31"
author: "Sam Schuster"
output:
  html_document: default
  pdf_document: default
  word_document: default
---
    
```{R echo = FALSE, warning = FALSE}
library(ggplot2)
library(nbastatR)
library(tidyverse)
library(dplyr)

GSW2010 <- teams_shots(teams = "Golden State Warriors", seasons = 2010)
GSW2011 <- teams_shots(teams = "Golden State Warriors",seasons = 2011)
GSW2012 <- teams_shots(teams = "Golden State Warriors",seasons = 2012)
GSW2013 <- teams_shots(teams = "Golden State Warriors",seasons = 2013)
GSW2014 <- teams_shots(teams = "Golden State Warriors",seasons = 2014)
GSW2015 <- teams_shots(teams = "Golden State Warriors",seasons = 2015)
GSW2016 <- teams_shots(teams = "Golden State Warriors",seasons = 2016)
GSW2017 <- teams_shots(teams = "Golden State Warriors",seasons = 2017)
GSW2018 <- teams_shots(teams = "Golden State Warriors",seasons = 2018)
GSW2019 <- teams_shots(teams = "Golden State Warriors",seasons = 2019)
GSW2020 <- teams_shots(teams = "Golden State Warriors",seasons = 2020)
GSW2021 <- teams_shots(teams = "Golden State Warriors", seasons = 2021)

GSW <- bind_rows(GSW2010,GSW2011,GSW2012,GSW2013,GSW2014,GSW2015,GSW2016,GSW2017,GSW2018,GSW2019,GSW2020,GSW2021)

factor(GSW$isShotMade) #To make shot color a continuous variable
My_shotchart <- ggplot(GSW, aes(x=(locationX/10)+25, y = (locationY/10)+4.6))+ #To fix the coordinate X for a basketball court, it was nescessary to add 25 so that it would be in a 0 to 50 ft court. The Y-coordinate took the basketball rim as the (0,0) coordinate, so to correct this I found the minimum Y-value and divided it by 10 and plused it to the location Y to make it fit into my court. 
   
##The following code is used to produce the image of a basketball court on my plots
   #NBA Court Boundaries
    geom_segment(aes(x = 0, y = 0, xend = 0, yend = 47)) +   #Left
    geom_segment(aes(x = 50, y =47, xend = 50, yend = 0)) +  #Right
    geom_segment(aes(x = 0, y = 47, xend = 50, yend = 47)) + #Top/Half-court line
    geom_segment(aes(x = 0, y = 0, xend = 50, yend = 0), color = 'black') +   #Bottom
    #Free-throw
        #Line
    geom_segment(aes(x = 19, y = 19, xend = 31, yend = 19)) +
        #Top circle
    geom_curve(aes(x = 19, y = 19, xend = 31, yend = 19), curvature = -1,
               lineend = 'round', color = 'black') +
        #Bottom circle  
    geom_curve(aes(x = 19, y = 19, xend = 31, yend = 19), curvature = 1,
               linetype = 2, lineend = 'round') +
    #Key
    geom_segment(aes(x = 17, y = 19, xend = 33, yend = 19)) + #Top
    geom_segment(aes(x = 17, y = 0, xend = 17, yend = 19)) +  #Left
    geom_segment(aes(x = 33, y = 0, xend = 33, yend = 19)) +  #Right
    #3-point Line
    geom_segment(aes(x = 3, y = 0, xend = 3, yend = 14)) +   #Left
    geom_segment(aes(x = 47, y = 0, xend = 47, yend = 14)) + #Right
    geom_curve(aes(x = 3, y = 14, xend = 47, yend = 14), curvature = -.75,
               angle = 90) + #Curve
    #Backboard
    geom_segment(aes(x = 22, y = 4, xend = 28, yend = 4)) +
    #Themes
    coord_fixed()+
   
   ##The following code is used to plot the shots on my graph
   geom_point(aes(col=isShotMade), size = .25, alpha = .5)+
   scale_color_manual(values = c("Gold","Blue"),name = "Shot Outcome",labels = c("Miss","Make"))+
   ggtitle("Golden State Warriors Shotchart 2010-2021")+
   ylab("Length Location of Shot")+
   xlab("Width Location of Shot")+
   facet_wrap(~yearSeason,nrow = 2)

My_shotchart
```


Report of Findings
   -In general more shots are missed than made.
   
   -Shots taken near the 3-point line tend to result in more misses than makes.
   
   -From 2010 to 2021, the shots attempted moved more towards the 3-point line.
   
   -Very few shots were taken past the half-court line, and these shots almost always resulted in a miss.
   
   -From 2020 to 2021 seemed to be the biggest change in location of shots taken.
   
Deeper Into the Report of Findings
   -More shots being missed than made would make sense when you look into the percentage of shots made on average. When looking into the average shooting percentage in the NBA, typically only 40-50% of shots go in, and usually less than 50%. The trend found in the shot chart displays this well, as you can easily tell that there are overall more misses than makes. 
   
   -3-point shots are in general a much more difficult shot than those taken inside the paint, so it makes sense there are more misses here. Even with the Warriors having good 3-point shooters in Stephen Curry and Klay Thompson during these years, these baskets still tend to go in at a lower rate. This would make sense why it is worth more points then as it can be difficult for players to be able to make these while being defended. 
   
   -The shots moving towards the 3-point line can be a direct factor of Stephen Curry joining the team and the trend of the NBA moving to more 3-point shots. Stephen Curry is one of, if not the greatest 3-point shooter of all time. As he gained prowess in his career, the shots taken by the Warriors moved more and more towards perimeter shots. This makes sense since Curry takes many 3-point attempts, along with his fellow splash-brother Klay Thompson. The NBA has been moving away from in the paint shots as well and more towards 3-point     attempts, which is also shown through the trend of shot locations the since 2010.
   
   -Most shots taken past the half-court line tend to be for a buzzer-beater shot, which are near impossible to make. This explains why almost every shot taken past the half-court or at the half-court line resulted in a miss, and why very few of these shots were even attempted. One thing to note is that more of these shots were made after the 2010 season. This could be due to Stephen Curry becoming a better shooter so he was able to make a few of these shots. However, even a shooter with Curry's ability should not attempt these shots very often as they are unlikely to result in a make.
   
   -The location of shots being took may have changed the most between 2020 and 2021 due to the effect that covid-19 had on the entire NBA. Since this season occurred in what is referred to as "The Bubble", players were able to perform better due to lack of crowd and lack of distractions. This year also acted as an experimental year for most as well, so players were taking more 3-point attempts. It is also worth noting that a lot of the three-point attempts were missed in 2020, and this could be due to Stephen Curry missing the majority of that season.

4. (10 points) Above and Beyond. Explore the data a bit, and create a graphic that uses (or incorporates) different information than what was used above. Some notes:

   - Create an additional graphic that incorporates at least one additional variable not previously used. The additional data should be drawn from a different dataset (function call) than the original graphic used. These two (or more) datasets may need to be joined appropriately.
   - You can either add more information to the plot above, or create a different plot. 
   - Formatting, labelling, etc. are all important here too.
   - Adding marginal densities or other "bells and whistles" might offer additional insight.
   - This graphic should be included at the end of the report (after the more detailed explanations). 
   - You should include a brief description of the graphic (highlighting the different/additional information used).

```{R echo = FALSE, warning = FALSE}
#The following code is to obtain annual season stats for the Golden State Warriors from the years 2000-2020
stats <- teams_annual_stats(teams = "Golden State Warriors", all_active_teams = FALSE)%>%
   filter(nameTeam =="Golden State Warriors",slugSeason >= 2000, slugSeason <= 2021)

#The following is used to create a data frame containing only the statistics that I want to include in my graph
warriors_data <- data_frame(shots = stats$fga, wins = stats$wins,year = stats$slugSeason)

#The following plots and labels my graph
ggplot(warriors_data, aes(x = shots, y = wins,color = factor(year))) +
  geom_point() +
   scale_color_discrete(name = "Season")+
  labs(x = "Shots", y = "Wins", title = "Golden State Warriors Wins vs Shots Taken (2000-2021)")+
   theme_dark()


```
This graph takes inspiration from Wayne Gretzky's famous quote, "You miss 100% of the shots you don't take." This graph shows that there seems to be a direct translation in the amount of shots taken compared to the amount of wins the Warriors have had since the 2000-2001 season. Most of the seasons that the Warriors had a good season in terms of wins was when they attempted a high amount of shots. Likewise, some of their worst season finishes less shots taken. This graph tells us that we should have a high number of attempted shots, granted they are good shots. 

1. Upload your report and code file(s) to GitHub by 11:59am (noon) on Friday, March 31.
2. Submit (on Canvas) your report, code, and link to your GitHub repository by 11:59am (noon) on Friday, March 31.
  
  
  
  


